### ISSUE TITLE
NXDL syntax error in NXreflections

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#572]
although reported result was *passing*, travis-ci log shows this ERROR:

```
======================================================================

ERROR: test__3__contributed_definitions__NXreflections (test_nxdl.Individual_NXDL_Tests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nexusformat/definitions/utils/test_nxdl.py", line 90, in test_wrap

    validate_xml(nxdl_file_name)

  File "/home/travis/build/nexusformat/definitions/utils/test_nxdl.py", line 61, in validate_xml

    raise NXDL_Invalid(msg)

NXDL_Invalid: contributed_definitions/NXreflections.nxdl.xml : Element '{http://definition.nexusformat.org/nxdl/3.1}dimensions': This element is not expected. Expected is one of ( {http://definition.nexusformat.org/nxdl/3.1}attribute, {http://definition.nexusformat.org/nxdl/3.1}enumeration )., line 38
```

**Comment by prjemian** [comment]
@phyy-nx : I will move the location of all *definitions* elements to before the *attribute* element.  This is a detail of the NXDL specification that would be nice to relax but that's for later.

**Comment by phyy-nx** [comment]
Awesome.  Thanks!
