### ISSUE TITLE
some unit tests fail since flexible names are UPPER case

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#714]
some [unit tests fail](https://travis-ci.org/nexusformat/definitions/jobs/640676114?utm_medium=notification&utm_source=github_status) since #562:

```
======================================================================

FAIL: test_application_definition_NXcanSAS (test_nxdl2rst.Issue_524_Clarify_Optional_or_Required)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nexusformat/definitions/utils/test_nxdl2rst.py", line 82, in test_application_definition_NXcanSAS

    self.apply_tests('applications', 'NXcanSAS', expected_lines)

  File "/home/travis/build/nexusformat/definitions/utils/test_nxdl2rst.py", line 94, in apply_tests

    self.assertTrue(line.strip() in printed_lines, line.strip())

AssertionError: **(entry)**: (required) :ref:`NXentry`

======================================================================

FAIL: test_base_class_NXentry (test_nxdl2rst.Issue_524_Clarify_Optional_or_Required)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nexusformat/definitions/utils/test_nxdl2rst.py", line 48, in test_base_class_NXentry

    self.apply_tests('base_classes', 'NXentry', expected_lines)

  File "/home/travis/build/nexusformat/definitions/utils/test_nxdl2rst.py", line 94, in apply_tests

    self.assertTrue(line.strip() in printed_lines, line.strip())

AssertionError: **(data)**: (optional) :ref:`NXdata`
```

**Comment by prjemian** [comment]
They fail because the expected names should now be upper case.  Here are the current expected names that fail:

```
        **(entry)**: (required) :ref:`NXentry`
        **(data)**: (required) :ref:`NXdata`
        **(data)**: (optional) :ref:`NXdata`
        **(sample)**: (optional) :ref:`NXsample`
        **(instrument)**: (optional) :ref:`NXinstrument`
        **(note)**: (optional) :ref:`NXnote`
        **(process)**: (optional) :ref:`NXprocess`
        **(source)**: (optional) :ref:`NXsource`
```
