### ISSUE TITLE
GitHub API authentication has changed : affects the release process

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#728]
Seems the GitHub API might have changed:

```
(base) mintadmin@mint-vm:~/.../NeXus/definitions$ utils/create_release_notes.py 
usage: create_release_notes.py [-h] [--head [HEAD]] base milestone
create_release_notes.py: error: the following arguments are required: base, milestone
(base) mintadmin@mint-vm:~/.../NeXus/definitions$ utils/create_release_notes.py "NXDL 2018.5" "NXDL 2020.1"
Traceback (most recent call last):
  File "utils/create_release_notes.py", line 213, in <module>
    main(cmd.base, head=cmd.head, milestone=cmd.milestone)
  File "utils/create_release_notes.py", line 184, in main
    notes.learn()
  File "utils/create_release_notes.py", line 109, in learn
    compare = self.repo.compare(self.base, self.head)
  File "/home/mintadmin/Apps/anaconda/lib/python3.7/site-packages/github/Repository.py", line 828, in compare
    self.url + "/compare/" + base + "..." + head
  File "/home/mintadmin/Apps/anaconda/lib/python3.7/site-packages/github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/mintadmin/Apps/anaconda/lib/python3.7/site-packages/github/Requester.py", line 286, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/commits/#compare-two-commits'}
```

**Comment by prjemian** [comment]
related? https://stackoverflow.com/questions/51639778/get-a-user-information-in-github-using-pygithub

**Comment by prjemian** [comment]
Fails on this line: https://github.com/nexusformat/definitions/blob/4f6ef8d592feffbef5f2d8af947f72d794656dc9/utils/create_release_notes.py#L109

where https://github.com/nexusformat/definitions/blob/4f6ef8d592feffbef5f2d8af947f72d794656dc9/utils/create_release_notes.py#L103-L104

* get_user(): https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_user
* compare(): https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.compare


In pyGitHub

**Comment by prjemian** [comment]
GitHub's API has [changed](https://developer.github.com/v3/auth/#via-username-and-password):

> Deprecation Notice: GitHub will discontinue password authentication to the API. You must now authenticate to the GitHub API with an API token, such as an OAuth access token, GitHub App installation access token, or personal access token, depending on what you need to do with the token.

**Comment by prjemian** [comment]
Created personal access token, using in the creds file instead of password, still  404 error.

**Comment by prjemian** [comment]
notes:

Accoring to the first article below, shared SSH keys work with the git push process but are not enough for the GitHub API.  That's where PAT (personal access token) comes in.

* https://happygitwithr.com/github-pat.html
* https://www.programmableweb.com/news/how-to-do-github-api-authentication-using-oauth-20/how-to/2017/09/24

**Comment by prjemian** [comment]
relevant?

https://github.com/PyGithub/PyGithub/pull/599#issue-131456325

```ipython
>>> github_client =  github.Github(login_or_token=pat, base_url=ghe_url)
>>> org = github_client.get_organization(org_name)
```

**Comment by prjemian** [comment]
[github3](https://github3py.readthedocs.io) is an alternative library to [pyGithub](https://pygithub.readthedocs.io) but the real problem here is authentication.

**Comment by prjemian** [comment]
This [advice](https://pygithub.readthedocs.io/en/latest/introduction.html#very-short-tutorial) works with my PAT (token)[https://github.com/settings/tokens]:

```
import github
g = github.Github(MY_PAT)
g.get_user().get_repos()
for r in g.get_user().get_repos():
    print(r.name)
```

Re-write the code, making it simpler to follow, using PAT authentication, and using logging.

**Comment by prjemian** [comment]
Successful revision possible with pyGithub package.  Still using that, no plans switching to github3 at this time.
